src := $(shell echo src/*.c)

objs := $(src:src/%.c=obj/%.o)

out := bin/myAlign

libs := -ldl -lm
includes := -Iinclude
cflags := -O3 -g

main : $(out)

$(out) : $(objs) 
	gcc -o $(out) $(objs) $(libs) $(includes) $(cflags)

obj/%.o : src/%.c
	gcc -c $< -o $@ $(libs) $(includes) $(cflags)

clean : 
	rm $(objs) $(out)
